let myAge = 26; //My age in years
let earlyYears = 2;  //uhhh 2. 
let laterYears = myAge - 2; // My age minus 2?\
let myAgeInDogYears; //adds together early and late years which equals my age in dog years.

let myName; //My name but its going to be all lowercase letters.

earlyYears *= 10.5;

laterYears *= 4; //multiplyes my later years by 4

console.log(earlyYears);
console.log(laterYears);

myAgeInDogYears = earlyYears + laterYears;

myName = 'Spencer'.toLowerCase();

console.log(`My name is ${myName}. I am ${myAge} years old in human years which is ${myAgeInDogYears} years old in dog years.`)